version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: "America/Chicago"
  open-pull-requests-limit: 10
  assignees:
  - stevenkuhn