global using Bogus;
global using LiteDB;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using Moq;
global using NCrunch.Framework;
global using Newtonsoft.Json;
global using OpenIddict.Abstractions;
global using OpenIddict.Core;
global using Sknet.OpenIddict.LiteDB.Models;
global using Sknet.OpenIddict.LiteDB.Tests.Builders;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Globalization;
global using System.Runtime.CompilerServices;
global using System.Text.Json;
global using VerifyTests;
global using VerifyXunit;
global using Xunit;
global using Xunit.Abstractions;
global using Xunit.Sdk;
global using static OpenIddict.Abstractions.OpenIddictConstants;
global using static Sknet.OpenIddict.LiteDB.Tests.Verifier;
global using static VerifyXunit.Verifier;
