global using LiteDB;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using Moq;
global using OpenIddict.Abstractions;
global using OpenIddict.Core;
global using Sknet.OpenIddict.LiteDB.Models;
global using Xunit;
global using VerifyXunit;
global using VerifyTests;
global using AutoBogus;
global using Bogus;
global using LiteDB.Engine;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Globalization;
global using System.Text.Json;
global using JsonSerializer = System.Text.Json.JsonSerializer;
global using static VerifyXunit.Verifier;