name: Build

on: [push]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs: 
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build and test
      run: ./build.ps1 --target Test PublishArtifacts

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: artifacts
        retention-days: 1

  create_release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs: [ build ]
    concurrency: build_${{ github.ref }}

    # only run this for a push to the main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: artifacts

    - name: Create release
      run: > 
        ./build.sh 
        --target PublishToGitHub 
        --skip PublishArtifacts
        --github-access-token ${{ secrets.GITHUB_TOKEN }}
        --github-repository ${{ github.repository }}
